apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-mlopscase.fullname" . }}
  labels:
    {{- include "chart-mlopscase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart-mlopscase.selectorLabels" . | nindent 4 }}
