prometheus:
  #service:
  #  type: LoadBalancer
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList: |
        - job_name: "fastapi"
        kubernetes_sd_configs:
        - role: "pod"
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: chart-mlopscase
            action: keep
