apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJV2RaMDJHc2pSWkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFd01qY3lNRFF6TkRKYUZ3MHpOREV3TWpVeU1EUTROREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMyb1daU0szY1ZJY3YxUUZCaUoxSXd6ajNRM0p3M0ZNaUhvaXRBcG9mcDVQUUV4T0VCejdIejlqY2EKSWNJdjBhRE5icUgrY3lOd3NTT2FEdnJ3UGpUQ2xmUE80cnRFaXF0NFlKNGZjRGtuTXcwbEREbmFSanQ3SUNRZAo0aGZiKzRnYzRHMGZodS9nM0dxZHZvMElHSEpWVE5zS0RyLzd0anJkR1Byd3JrSXdyc21VRmFzVDJ6T2hXUnh2CkNMODdpZnByTTM3b0gzcEJ3K0I2R0VnUVovWjhRcVl0RHFnVHV2MTZXOGdhVzhSVzNpRkdBK1ZSaFpYaEZ6OUsKSmxmTFFwaUN5RnNSSmFIeWR0V05aY0dRM0J4NHZqcEpGS3RhaE9wK2s3WkdkNVIvcVRGSFVnUHRSU0VDelU1ZQovbzNXMldjOFZQdnhQT0NjRy9lSVZoNm9Dd1c5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSMDZrUGd0Z1NUNWZTSDU3ZXM0ZVFlWkdJUzVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2FRVXlPaUtrRgpxWnpUNkNnV3FpeW1IRWhPS0gvS3BKaVRzUGVmcXd6VzVxcnhiejgrSTBiM1VKNmp6TE5pbDNkM29XQ3VoS1MwCnFKS1BoenA4WHBROHZzV1RQQ0Q5T0Q0ZVNLZncxUHlwMEhyeHpUNHlDMFV6bzJ6QmtEK2J4a3Y0UHh4WEY4ZHoKTHhIZWFZQ3pDSGkyUlo2TUdMcGgwaGg4c2VnWFRIcEJNTm9EYk1jZmU3SlppQ0w4VDZzck5CbnZyZ1NRNlNpegpDQ1BPbVpMQk55cEpMZlBQaFhMMUYzcW5OUHNzc2E3WkFVUmF5VmthSDh0cWFVbExJNGtnYnEyNi9JTmd3dHRnCkhkQ2Y4djh6a25vMXNIZzkyKzErNnFnV0V3QnQ4YjFEOU5lRDFaNllVVkxOL1lEZjJsTkZNYXp3dmpUcFNSSWMKU0ZrWUVON2drTFNVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0AA9C70629730029C0E0FFFD440443C9.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
    user: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
  name: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
current-context: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:183167903796:cluster/my-eks1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-eks1
      - --output
      - json
      command: aws